---
title: Pai.Fyi
timezone: Asia/Kolkata
collections:
  ideas:
    title: Ideas
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: "~"
author:
  twitter: sofasogo0d
  github: siddhartpai
  stackoverflow: 1220620
  email: your-id@your-email.com
copyright:
  year: 2017
  name: Siddharth
google-analytics:
  id: UA-179989149-1
disqus:
  id: siddhartpai
url: https://siddhartpai.github.io/pai.fyi
baseurl: "/"
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
nav:
- name: About
  url: "/about"
- name: Tags
  url: "/tags"
- name: Github
  url: https://github.com/siddhartpai
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-admin
exclude:
- vendor
